pipeline:
  name: terraform-harness-aws
  identifier: terraformharnessaws
  projectIdentifier: app01
  orgIdentifier: default
  tags: {}
  properties:
    ci:
        codebase:
            connectorRef: kundusogithub
            repoName: terraform-harness.io-aws
            build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Set AWS Credentials
                  identifier: aws_credentials
                  spec:
                    shell: Sh
                    command: |-
                      pwd
                      # echo "hello" >>test1.log
                      # echo <+variable.region> >>test1.log
                      # echo <+secrets.getValue("testsecret")> >>test1.log
                      # ls
                      cd infrastructure
                      ls
                      # aws --version >>test1.log
                      # cat test1.log
                      export AWS_ACCESS_KEY_ID=<+secrets.getValue("AWSSecretKey")>
                      export AWS_SECRET_ACCESS_KEY=<+secrets.getValue("AWSAccessKey")>
                      export AWS_DEFAULT_REGION=<+secrets.getValue("AWSRegion")>
              - step:
                  type: Run
                  name: Install Terragrunt
                  identifier: terragrunt_install
                  spec:
                    shell: Sh
                    command: |-
                      sudo wget -q -O /bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v0.38.4/terragrunt_linux_amd64"
                      sudo chmod +x /bin/terragrunt
                      terragrunt -v
              - step:
                  type: Run
                  name: Terragrunt Init
                  identifier: terragrunt_init
                  spec:
                    shell: Sh
                    command: |-
                      cd environments/AccountA
                      pwd
                      ls
                      terragrunt init --terragrunt-non-interactive --terragrunt-iam-role "arn:aws:iam::<+secrets.getValue("devawsaccountnumber"):role/terragrunt-role"
              - step:
                  type: Run
                  name: Check files in root
                  identifier: check_files
                  spec:
                    shell: Sh
                    command: |-
                      pwd
                      ls
                      echo <+trigger.branch>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
