pipeline:
  name: terraform-harness-aws
  identifier: terraformharnessaws
  projectIdentifier: app01
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Terraform init
        identifier: Terraform_init
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: script_run
                  identifier: script_run
                  spec:
                    shell: Bash
                    source:
                      type: Inline
                      spec:
                        script: pwd
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        failureStrategies:
          - onFailure:
              action:
                type: MarkAsFailure
              errors:
                - AllErrors
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
