pipeline:
  name: terraform-harness-aws
  identifier: terraformharnessaws
  projectIdentifier: app01
  orgIdentifier: default
  tags: {}
  properties:
    ci:
        codebase:
            connectorRef: kundusogithub
            repoName: terraform-harness.io-aws
            build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: pwd
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}