pipeline:
  name: terraform-harness-aws
  identifier: terraformharnessaws
  projectIdentifier: app01
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: run script
        identifier: run_script
        description: run-script
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          pwd
                          ls
                          echo "checking execution"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}