pipeline:
  name: terraform-harness-aws
  identifier: terraformharnessaws
  projectIdentifier: app01
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: kunduso
        build: <+input>
  stages:
    - stage:
        name: Terraform init
        identifier: Terraform_init
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone
                  identifier: GitClone
                  spec:
                    connectorRef: kunduso
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Terraform init
                  identifier: Terraform_init
                  spec:
                    connectorRef: account.harnessImage
                    image: latest
                    shell: Sh
                    command: terraform init
              - step:
                  type: Run
                  name: Terraform Validate
                  identifier: Terraform_Validate
                  spec:
                    connectorRef: account.harnessImage
                    image: latest
                    shell: Sh
                    command: terraform validate
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
